# --- Window and Layout ---
INITIAL_WIN_WIDTH, INITIAL_WIN_HEIGHT = 1280, 720
TOP_BAR_HEIGHT = 40
TOOLBAR_HEIGHT = 40
RIGHT_PANEL_WIDTH = 280
PREVIEW_SIZE = (240, 240)

# --- Isometric Grid ---
TILE_WIDTH, TILE_HEIGHT = 64, 32
TILE_WIDTH_HALF, TILE_HEIGHT_HALF = TILE_WIDTH // 2, TILE_HEIGHT // 2
WALL_HEIGHT = 96

# --- Colors ---
COLOR_BG = (20, 30, 40)
COLOR_TOP_BAR = (30, 40, 50)
COLOR_PANEL_BG = (35, 45, 55)
COLOR_EDITOR_BG = (45, 55, 65)
COLOR_PREVIEW_BG = (0, 0, 0)
COLOR_BORDER = (80, 90, 100)
COLOR_BUTTON = (70, 80, 90)
COLOR_BUTTON_HOVER = (100, 110, 120)
COLOR_BUTTON_ACTIVE = (120, 130, 140)
COLOR_TEXT = (200, 200, 210)
COLOR_INFO_TEXT = (130, 140, 150)
COLOR_TITLE_TEXT = (150, 160, 170)
COLOR_ANCHOR = (255, 100, 100)
COLOR_INPUT_ACTIVE = (230, 230, 230)
COLOR_INPUT_INACTIVE = (150, 150, 150)
COLOR_TILE = (180, 140, 100)
COLOR_TILE_BORDER = (100, 100, 100)
COLOR_ORIGIN = (100, 120, 140)
COLOR_HOVER_BORDER = (255, 255, 0)
COLOR_WALL = (200, 120, 50)
COLOR_WALL_BORDER = (140, 80, 30)
COLOR_PREVIEW_OUTLINE = (220, 220, 220)
COLOR_SAVE_CONFIRM_BG = (50, 60, 70, 220)

# --- Tile Types ---
TILE_TYPE_FULL = 1
TILE_TYPE_CORNER_NO_TL = 2
TILE_TYPE_CORNER_NO_TR = 3
TILE_TYPE_CORNER_NO_BR = 4
TILE_TYPE_CORNER_NO_BL = 5
TILE_TYPES = [TILE_TYPE_FULL, TILE_TYPE_CORNER_NO_TL, TILE_TYPE_CORNER_NO_TR, TILE_TYPE_CORNER_NO_BR, TILE_TYPE_CORNER_NO_BL]

# --- Structure Edit Modes ---
MODE_TILES = 0
MODE_WALLS = 1

# --- Wall Edges ---
EDGE_NE = "ne"; EDGE_SE = "se"; EDGE_SW = "sw"; EDGE_NW = "nw"
EDGE_DIAG_SW_NE = "diag_sw_ne" # Diagonal Vertical (Bottom <-> Top)
EDGE_DIAG_NW_SE = "diag_nw_se" # Diagonal Horizontal (Left <-> Right)

# --- MAPPING TILE TYPES TO THEIR VALID EDGES ---
TILE_TYPE_EDGES = {
    TILE_TYPE_FULL: [EDGE_NE, EDGE_SE, EDGE_SW, EDGE_NW],
    TILE_TYPE_CORNER_NO_TL: [EDGE_NE, EDGE_SE, EDGE_DIAG_SW_NE],
    # --- LÍNEAS CORREGIDAS ---
    TILE_TYPE_CORNER_NO_TR: [EDGE_NW, EDGE_SW, EDGE_DIAG_SW_NE], # Diagonal Vertical
    TILE_TYPE_CORNER_NO_BR: [EDGE_NW, EDGE_NE, EDGE_DIAG_NW_SE], # Diagonal Horizontal
    # --- FIN DE LÍNEAS CORREGIDAS ---
    TILE_TYPE_CORNER_NO_BL: [EDGE_SE, EDGE_SW, EDGE_DIAG_NW_SE],
}

# --- Main Editor Modes ---
EDITOR_MODE_LAYOUT = 0
EDITOR_MODE_OBJECTS = 1